//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Exemplo.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using System;
using System.IO;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
public partial class ExemploLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		ASSIGNMENT=1, PLUS_ASSIGNMENT=2, MINUS_ASSIGNMENT=3, DIV_ASSIGNMENT=4, 
		TIMES_ASSIGNMENT=5, GT=6, GE=7, LT=8, LE=9, EQ=10, NEQ=11, PLUS=12, MINUS=13, 
		DIV=14, TIMES=15, POW=16, LBRACE=17, RBRACE=18, LPAREN=19, RPAREN=20, 
		SEMI=21, COMMA=22, WHITESPACE=23, SINGLE_LINE_COMMENT=24, DELIMITED_COMMENT=25, 
		AND=26, OR=27, IF=28, ELSE=29, WHILE=30, EXTERNAL=31, COALESCE_OPERATOR=32, 
		NULL=33, VAR=34, NUMBER=35, VARIABLE=36, TEXT=37;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"ASSIGNMENT", "PLUS_ASSIGNMENT", "MINUS_ASSIGNMENT", "DIV_ASSIGNMENT", 
		"TIMES_ASSIGNMENT", "GT", "GE", "LT", "LE", "EQ", "NEQ", "PLUS", "MINUS", 
		"DIV", "TIMES", "POW", "LBRACE", "RBRACE", "LPAREN", "RPAREN", "SEMI", 
		"COMMA", "WHITESPACE", "SINGLE_LINE_COMMENT", "DELIMITED_COMMENT", "AND", 
		"OR", "IF", "ELSE", "WHILE", "EXTERNAL", "COALESCE_OPERATOR", "NULL", 
		"VAR", "NUMBER", "VARIABLE", "TEXT"
	};


	public ExemploLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ExemploLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "'+='", "'-='", "'/='", "'*='", "'>'", "'>='", "'<'", "'<='", 
		"'=='", "'!='", "'+'", "'-'", "'/'", "'*'", "'^'", "'{'", "'}'", "'('", 
		"')'", "';'", "','", null, null, null, "'&&'", "'||'", "'if'", "'else'", 
		"'while'", "'@'", "'??'", "'null'", "'var'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "ASSIGNMENT", "PLUS_ASSIGNMENT", "MINUS_ASSIGNMENT", "DIV_ASSIGNMENT", 
		"TIMES_ASSIGNMENT", "GT", "GE", "LT", "LE", "EQ", "NEQ", "PLUS", "MINUS", 
		"DIV", "TIMES", "POW", "LBRACE", "RBRACE", "LPAREN", "RPAREN", "SEMI", 
		"COMMA", "WHITESPACE", "SINGLE_LINE_COMMENT", "DELIMITED_COMMENT", "AND", 
		"OR", "IF", "ELSE", "WHILE", "EXTERNAL", "COALESCE_OPERATOR", "NULL", 
		"VAR", "NUMBER", "VARIABLE", "TEXT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Exemplo.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ExemploLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\'', '\xE3', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x18', '\x6', '\x18', '\x83', '\n', '\x18', '\r', '\x18', 
		'\xE', '\x18', '\x84', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\a', '\x19', '\x8D', '\n', '\x19', 
		'\f', '\x19', '\xE', '\x19', '\x90', '\v', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\a', 
		'\x1A', '\x98', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\x9B', '\v', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', 
		'\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '#', 
		'\x3', '#', '\x3', '#', '\x3', '#', '\x3', '$', '\x5', '$', '\xC5', '\n', 
		'$', '\x3', '$', '\x6', '$', '\xC8', '\n', '$', '\r', '$', '\xE', '$', 
		'\xC9', '\x3', '$', '\x3', '$', '\x6', '$', '\xCE', '\n', '$', '\r', '$', 
		'\xE', '$', '\xCF', '\x5', '$', '\xD2', '\n', '$', '\x3', '%', '\x3', 
		'%', '\a', '%', '\xD6', '\n', '%', '\f', '%', '\xE', '%', '\xD9', '\v', 
		'%', '\x3', '&', '\x3', '&', '\a', '&', '\xDD', '\n', '&', '\f', '&', 
		'\xE', '&', '\xE0', '\v', '&', '\x3', '&', '\x3', '&', '\x5', '\x8E', 
		'\x99', '\xDE', '\x2', '\'', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', 
		')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', 
		' ', '?', '!', '\x41', '\"', '\x43', '#', '\x45', '$', 'G', '%', 'I', 
		'&', 'K', '\'', '\x3', '\x2', '\x6', '\x5', '\x2', '\v', '\f', '\xE', 
		'\xF', '\"', '\"', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x43', '\\', 
		'\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', '\\', 
		'\x61', '\x61', '\x63', '|', '\x2', '\xEB', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x3', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\x5', 'O', '\x3', '\x2', '\x2', '\x2', '\a', 'R', '\x3', 
		'\x2', '\x2', '\x2', '\t', 'U', '\x3', '\x2', '\x2', '\x2', '\v', 'X', 
		'\x3', '\x2', '\x2', '\x2', '\r', '[', '\x3', '\x2', '\x2', '\x2', '\xF', 
		']', '\x3', '\x2', '\x2', '\x2', '\x11', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x13', '\x62', '\x3', '\x2', '\x2', '\x2', '\x15', '\x65', '\x3', '\x2', 
		'\x2', '\x2', '\x17', 'h', '\x3', '\x2', '\x2', '\x2', '\x19', 'k', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', 'm', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'o', '\x3', '\x2', '\x2', '\x2', '\x1F', 'q', '\x3', '\x2', '\x2', '\x2', 
		'!', 's', '\x3', '\x2', '\x2', '\x2', '#', 'u', '\x3', '\x2', '\x2', '\x2', 
		'%', 'w', '\x3', '\x2', '\x2', '\x2', '\'', 'y', '\x3', '\x2', '\x2', 
		'\x2', ')', '{', '\x3', '\x2', '\x2', '\x2', '+', '}', '\x3', '\x2', '\x2', 
		'\x2', '-', '\x7F', '\x3', '\x2', '\x2', '\x2', '/', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\x88', '\x3', '\x2', '\x2', '\x2', '\x33', '\x93', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\xA1', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\xA4', '\x3', '\x2', '\x2', '\x2', '\x39', '\xA7', '\x3', '\x2', 
		'\x2', '\x2', ';', '\xAA', '\x3', '\x2', '\x2', '\x2', '=', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '?', '\xB5', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\x43', '\xBA', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\xBF', '\x3', '\x2', '\x2', '\x2', 'G', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', 'I', '\xD3', '\x3', '\x2', '\x2', '\x2', 'K', '\xDA', 
		'\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', '?', '\x2', '\x2', 'N', '\x4', 
		'\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', '-', '\x2', '\x2', 'P', 'Q', 
		'\a', '?', '\x2', '\x2', 'Q', '\x6', '\x3', '\x2', '\x2', '\x2', 'R', 
		'S', '\a', '/', '\x2', '\x2', 'S', 'T', '\a', '?', '\x2', '\x2', 'T', 
		'\b', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '\x31', '\x2', '\x2', 
		'V', 'W', '\a', '?', '\x2', '\x2', 'W', '\n', '\x3', '\x2', '\x2', '\x2', 
		'X', 'Y', '\a', ',', '\x2', '\x2', 'Y', 'Z', '\a', '?', '\x2', '\x2', 
		'Z', '\f', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', '@', '\x2', '\x2', 
		'\\', '\xE', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '@', '\x2', '\x2', 
		'^', '_', '\a', '?', '\x2', '\x2', '_', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x61', '\a', '>', '\x2', '\x2', '\x61', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x63', '\a', '>', '\x2', '\x2', '\x63', '\x64', '\a', 
		'?', '\x2', '\x2', '\x64', '\x14', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x66', '\a', '?', '\x2', '\x2', '\x66', 'g', '\a', '?', '\x2', '\x2', 
		'g', '\x16', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\a', '#', '\x2', '\x2', 
		'i', 'j', '\a', '?', '\x2', '\x2', 'j', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'k', 'l', '\a', '-', '\x2', '\x2', 'l', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		'm', 'n', '\a', '/', '\x2', '\x2', 'n', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'o', 'p', '\a', '\x31', '\x2', '\x2', 'p', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\a', ',', '\x2', '\x2', 'r', ' ', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\a', '`', '\x2', '\x2', 't', '\"', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'v', '\a', '}', '\x2', '\x2', 'v', '$', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\a', '\x7F', '\x2', '\x2', 'x', '&', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'z', '\a', '*', '\x2', '\x2', 'z', '(', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\a', '+', '\x2', '\x2', '|', '*', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\a', '=', '\x2', '\x2', '~', ',', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x80', '\a', '.', '\x2', '\x2', '\x80', '.', '\x3', '\x2', 
		'\x2', '\x2', '\x81', '\x83', '\t', '\x2', '\x2', '\x2', '\x82', '\x81', 
		'\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', 
		'\x84', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\x3', '\x2', 
		'\x2', '\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', 
		'\b', '\x18', '\x2', '\x2', '\x87', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\x88', '\x89', '\a', '\x31', '\x2', '\x2', '\x89', '\x8A', '\a', '\x31', 
		'\x2', '\x2', '\x8A', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8D', 
		'\v', '\x2', '\x2', '\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', '\x2', 
		'\x8D', '\x90', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', 
		'\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x91', 
		'\x3', '\x2', '\x2', '\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', 
		'\x91', '\x92', '\b', '\x19', '\x2', '\x2', '\x92', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x93', '\x94', '\a', '\x31', '\x2', '\x2', '\x94', '\x95', 
		'\a', ',', '\x2', '\x2', '\x95', '\x99', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x98', '\v', '\x2', '\x2', '\x2', '\x97', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x97', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9D', '\a', ',', '\x2', '\x2', '\x9D', '\x9E', '\a', 
		'\x31', '\x2', '\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\xA0', '\b', '\x1A', '\x2', '\x2', '\xA0', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\xA2', '\a', '(', '\x2', '\x2', '\xA2', '\xA3', '\a', 
		'(', '\x2', '\x2', '\xA3', '\x36', '\x3', '\x2', '\x2', '\x2', '\xA4', 
		'\xA5', '\a', '~', '\x2', '\x2', '\xA5', '\xA6', '\a', '~', '\x2', '\x2', 
		'\xA6', '\x38', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\a', 'k', 
		'\x2', '\x2', '\xA8', '\xA9', '\a', 'h', '\x2', '\x2', '\xA9', ':', '\x3', 
		'\x2', '\x2', '\x2', '\xAA', '\xAB', '\a', 'g', '\x2', '\x2', '\xAB', 
		'\xAC', '\a', 'n', '\x2', '\x2', '\xAC', '\xAD', '\a', 'u', '\x2', '\x2', 
		'\xAD', '\xAE', '\a', 'g', '\x2', '\x2', '\xAE', '<', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB0', '\a', 'y', '\x2', '\x2', '\xB0', '\xB1', '\a', 
		'j', '\x2', '\x2', '\xB1', '\xB2', '\a', 'k', '\x2', '\x2', '\xB2', '\xB3', 
		'\a', 'n', '\x2', '\x2', '\xB3', '\xB4', '\a', 'g', '\x2', '\x2', '\xB4', 
		'>', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\a', '\x42', '\x2', 
		'\x2', '\xB6', '@', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\a', 
		'\x41', '\x2', '\x2', '\xB8', '\xB9', '\a', '\x41', '\x2', '\x2', '\xB9', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\a', 'p', '\x2', 
		'\x2', '\xBB', '\xBC', '\a', 'w', '\x2', '\x2', '\xBC', '\xBD', '\a', 
		'n', '\x2', '\x2', '\xBD', '\xBE', '\a', 'n', '\x2', '\x2', '\xBE', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\a', 'x', '\x2', '\x2', '\xC0', 
		'\xC1', '\a', '\x63', '\x2', '\x2', '\xC1', '\xC2', '\a', 't', '\x2', 
		'\x2', '\xC2', '\x46', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC5', '\a', 
		'/', '\x2', '\x2', '\xC4', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xC5', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xC8', '\t', '\x3', '\x2', '\x2', '\xC7', '\xC6', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCA', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xCD', '\a', 
		'\x30', '\x2', '\x2', '\xCC', '\xCE', '\t', '\x3', '\x2', '\x2', '\xCD', 
		'\xCC', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCF', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xCB', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD2', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', 'H', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD7', '\t', 
		'\x4', '\x2', '\x2', '\xD4', '\xD6', '\t', '\x5', '\x2', '\x2', '\xD5', 
		'\xD4', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD9', '\x3', '\x2', '\x2', 
		'\x2', '\xD7', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', 
		'\x2', '\x2', '\x2', '\xD8', 'J', '\x3', '\x2', '\x2', '\x2', '\xD9', 
		'\xD7', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDE', '\a', '$', '\x2', 
		'\x2', '\xDB', '\xDD', '\v', '\x2', '\x2', '\x2', '\xDC', '\xDB', '\x3', 
		'\x2', '\x2', '\x2', '\xDD', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xDE', 
		'\xDF', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xDC', '\x3', '\x2', '\x2', 
		'\x2', '\xDF', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xDE', '\x3', 
		'\x2', '\x2', '\x2', '\xE1', '\xE2', '\a', '$', '\x2', '\x2', '\xE2', 
		'L', '\x3', '\x2', '\x2', '\x2', '\f', '\x2', '\x84', '\x8E', '\x99', 
		'\xC4', '\xC9', '\xCF', '\xD1', '\xD7', '\xDE', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
