//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Exemplo.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class ExemploLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		ASSIGNMENT=1, PLUS_ASSIGNMENT=2, MINUS_ASSIGNMENT=3, DIV_ASSIGNMENT=4, 
		TIMES_ASSIGNMENT=5, GT=6, GE=7, LT=8, LE=9, EQ=10, NEQ=11, PLUS=12, MINUS=13, 
		DIV=14, TIMES=15, LBRACE=16, RBRACE=17, LPAREN=18, RPAREN=19, SEMI=20, 
		COMMA=21, WHITESPACE=22, SINGLE_LINE_COMMENT=23, DELIMITED_COMMENT=24, 
		AND=25, OR=26, IF=27, ELSE=28, WHILE=29, COALESCE_OPERATOR=30, NULL=31, 
		VAR=32, NUMBER=33, VARIABLE=34;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"ASSIGNMENT", "PLUS_ASSIGNMENT", "MINUS_ASSIGNMENT", "DIV_ASSIGNMENT", 
		"TIMES_ASSIGNMENT", "GT", "GE", "LT", "LE", "EQ", "NEQ", "PLUS", "MINUS", 
		"DIV", "TIMES", "LBRACE", "RBRACE", "LPAREN", "RPAREN", "SEMI", "COMMA", 
		"WHITESPACE", "SINGLE_LINE_COMMENT", "DELIMITED_COMMENT", "AND", "OR", 
		"IF", "ELSE", "WHILE", "COALESCE_OPERATOR", "NULL", "VAR", "NUMBER", "VARIABLE"
	};


	public ExemploLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ExemploLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "'+='", "'-='", "'/='", "'*='", "'>'", "'>='", "'<'", "'<='", 
		"'=='", "'!='", "'+'", "'-'", "'/'", "'*'", "'{'", "'}'", "'('", "')'", 
		"';'", "','", null, null, null, "'&&'", "'||'", "'if'", "'else'", "'while'", 
		"'??'", "'null'", "'var'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "ASSIGNMENT", "PLUS_ASSIGNMENT", "MINUS_ASSIGNMENT", "DIV_ASSIGNMENT", 
		"TIMES_ASSIGNMENT", "GT", "GE", "LT", "LE", "EQ", "NEQ", "PLUS", "MINUS", 
		"DIV", "TIMES", "LBRACE", "RBRACE", "LPAREN", "RPAREN", "SEMI", "COMMA", 
		"WHITESPACE", "SINGLE_LINE_COMMENT", "DELIMITED_COMMENT", "AND", "OR", 
		"IF", "ELSE", "WHILE", "COALESCE_OPERATOR", "NULL", "VAR", "NUMBER", "VARIABLE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Exemplo.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ExemploLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '$', '\xD0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', 
		'\x6', '\x17', '{', '\n', '\x17', '\r', '\x17', '\xE', '\x17', '|', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\a', '\x18', '\x85', '\n', '\x18', '\f', '\x18', '\xE', '\x18', 
		'\x88', '\v', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\a', '\x19', '\x90', '\n', '\x19', 
		'\f', '\x19', '\xE', '\x19', '\x93', '\v', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', 
		'\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '\"', 
		'\x5', '\"', '\xBB', '\n', '\"', '\x3', '\"', '\x6', '\"', '\xBE', '\n', 
		'\"', '\r', '\"', '\xE', '\"', '\xBF', '\x3', '\"', '\x3', '\"', '\x6', 
		'\"', '\xC4', '\n', '\"', '\r', '\"', '\xE', '\"', '\xC5', '\x5', '\"', 
		'\xC8', '\n', '\"', '\x3', '#', '\x3', '#', '\a', '#', '\xCC', '\n', '#', 
		'\f', '#', '\xE', '#', '\xCF', '\v', '#', '\x4', '\x86', '\x91', '\x2', 
		'$', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', 
		'\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', 
		'-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', 
		'\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', ' ', '?', '!', '\x41', 
		'\"', '\x43', '#', '\x45', '$', '\x3', '\x2', '\x6', '\x5', '\x2', '\v', 
		'\f', '\xE', '\xF', '\"', '\"', '\x3', '\x2', '\x32', ';', '\x5', '\x2', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x2', '\xD7', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', 
		';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\x3', 'G', '\x3', '\x2', '\x2', '\x2', '\x5', 'I', 
		'\x3', '\x2', '\x2', '\x2', '\a', 'L', '\x3', '\x2', '\x2', '\x2', '\t', 
		'O', '\x3', '\x2', '\x2', '\x2', '\v', 'R', '\x3', '\x2', '\x2', '\x2', 
		'\r', 'U', '\x3', '\x2', '\x2', '\x2', '\xF', 'W', '\x3', '\x2', '\x2', 
		'\x2', '\x11', 'Z', '\x3', '\x2', '\x2', '\x2', '\x13', '\\', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '_', '\x3', '\x2', '\x2', '\x2', '\x17', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\x65', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', 'g', '\x3', '\x2', '\x2', '\x2', '\x1D', 'i', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', 'k', '\x3', '\x2', '\x2', '\x2', '!', 'm', '\x3', '\x2', 
		'\x2', '\x2', '#', 'o', '\x3', '\x2', '\x2', '\x2', '%', 'q', '\x3', '\x2', 
		'\x2', '\x2', '\'', 's', '\x3', '\x2', '\x2', '\x2', ')', 'u', '\x3', 
		'\x2', '\x2', '\x2', '+', 'w', '\x3', '\x2', '\x2', '\x2', '-', 'z', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x80', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x33', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x37', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\xA2', '\x3', '\x2', '\x2', '\x2', ';', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '=', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '?', '\xB0', '\x3', '\x2', '\x2', '\x2', '\x41', '\xB5', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\xBA', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\xC9', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '?', '\x2', '\x2', 
		'H', '\x4', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', '-', '\x2', '\x2', 
		'J', 'K', '\a', '?', '\x2', '\x2', 'K', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\a', '/', '\x2', '\x2', 'M', 'N', '\a', '?', '\x2', '\x2', 
		'N', '\b', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', '\x31', '\x2', 
		'\x2', 'P', 'Q', '\a', '?', '\x2', '\x2', 'Q', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'S', '\a', ',', '\x2', '\x2', 'S', 'T', '\a', '?', '\x2', 
		'\x2', 'T', '\f', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '@', '\x2', 
		'\x2', 'V', '\xE', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', '@', '\x2', 
		'\x2', 'X', 'Y', '\a', '?', '\x2', '\x2', 'Y', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '[', '\a', '>', '\x2', '\x2', '[', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\a', '>', '\x2', '\x2', ']', '^', '\a', '?', '\x2', 
		'\x2', '^', '\x14', '\x3', '\x2', '\x2', '\x2', '_', '`', '\a', '?', '\x2', 
		'\x2', '`', '\x61', '\a', '?', '\x2', '\x2', '\x61', '\x16', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '\x63', '\a', '#', '\x2', '\x2', '\x63', '\x64', 
		'\a', '?', '\x2', '\x2', '\x64', '\x18', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x66', '\a', '-', '\x2', '\x2', '\x66', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'g', 'h', '\a', '/', '\x2', '\x2', 'h', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'j', '\a', '\x31', '\x2', '\x2', 'j', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', 'k', 'l', '\a', ',', '\x2', '\x2', 'l', ' ', '\x3', '\x2', 
		'\x2', '\x2', 'm', 'n', '\a', '}', '\x2', '\x2', 'n', '\"', '\x3', '\x2', 
		'\x2', '\x2', 'o', 'p', '\a', '\x7F', '\x2', '\x2', 'p', '$', '\x3', '\x2', 
		'\x2', '\x2', 'q', 'r', '\a', '*', '\x2', '\x2', 'r', '&', '\x3', '\x2', 
		'\x2', '\x2', 's', 't', '\a', '+', '\x2', '\x2', 't', '(', '\x3', '\x2', 
		'\x2', '\x2', 'u', 'v', '\a', '=', '\x2', '\x2', 'v', '*', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'x', '\a', '.', '\x2', '\x2', 'x', ',', '\x3', '\x2', 
		'\x2', '\x2', 'y', '{', '\t', '\x2', '\x2', '\x2', 'z', 'y', '\x3', '\x2', 
		'\x2', '\x2', '{', '|', '\x3', '\x2', '\x2', '\x2', '|', 'z', '\x3', '\x2', 
		'\x2', '\x2', '|', '}', '\x3', '\x2', '\x2', '\x2', '}', '~', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x7F', '\b', '\x17', '\x2', '\x2', '\x7F', '.', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '\x81', '\a', '\x31', '\x2', '\x2', '\x81', 
		'\x82', '\a', '\x31', '\x2', '\x2', '\x82', '\x86', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x85', '\v', '\x2', '\x2', '\x2', '\x84', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x88', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x86', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x89', '\x3', '\x2', '\x2', '\x2', '\x88', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x8A', '\b', '\x18', '\x2', '\x2', '\x8A', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', '\x31', '\x2', 
		'\x2', '\x8C', '\x8D', '\a', ',', '\x2', '\x2', '\x8D', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x90', '\v', '\x2', '\x2', '\x2', '\x8F', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '\x91', '\x92', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x92', '\x94', '\x3', '\x2', '\x2', '\x2', '\x93', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\a', ',', '\x2', 
		'\x2', '\x95', '\x96', '\a', '\x31', '\x2', '\x2', '\x96', '\x97', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\b', '\x19', '\x2', '\x2', '\x98', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '(', '\x2', 
		'\x2', '\x9A', '\x9B', '\a', '(', '\x2', '\x2', '\x9B', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9D', '\a', '~', '\x2', '\x2', '\x9D', 
		'\x9E', '\a', '~', '\x2', '\x2', '\x9E', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\xA0', '\a', 'k', '\x2', '\x2', '\xA0', '\xA1', '\a', 
		'h', '\x2', '\x2', '\xA1', '\x38', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA3', '\a', 'g', '\x2', '\x2', '\xA3', '\xA4', '\a', 'n', '\x2', '\x2', 
		'\xA4', '\xA5', '\a', 'u', '\x2', '\x2', '\xA5', '\xA6', '\a', 'g', '\x2', 
		'\x2', '\xA6', ':', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\a', 
		'y', '\x2', '\x2', '\xA8', '\xA9', '\a', 'j', '\x2', '\x2', '\xA9', '\xAA', 
		'\a', 'k', '\x2', '\x2', '\xAA', '\xAB', '\a', 'n', '\x2', '\x2', '\xAB', 
		'\xAC', '\a', 'g', '\x2', '\x2', '\xAC', '<', '\x3', '\x2', '\x2', '\x2', 
		'\xAD', '\xAE', '\a', '\x41', '\x2', '\x2', '\xAE', '\xAF', '\a', '\x41', 
		'\x2', '\x2', '\xAF', '>', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', 
		'\a', 'p', '\x2', '\x2', '\xB1', '\xB2', '\a', 'w', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', 'n', '\x2', '\x2', '\xB3', '\xB4', '\a', 'n', '\x2', '\x2', 
		'\xB4', '@', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\a', 'x', '\x2', 
		'\x2', '\xB6', '\xB7', '\a', '\x63', '\x2', '\x2', '\xB7', '\xB8', '\a', 
		't', '\x2', '\x2', '\xB8', '\x42', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBB', '\a', '/', '\x2', '\x2', '\xBA', '\xB9', '\x3', '\x2', '\x2', 
		'\x2', '\xBA', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBE', '\t', '\x3', '\x2', '\x2', '\xBD', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x3', '\x2', '\x2', 
		'\x2', '\xBF', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\x3', 
		'\x2', '\x2', '\x2', '\xC0', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC3', '\a', '\x30', '\x2', '\x2', '\xC2', '\xC4', '\t', '\x3', '\x2', 
		'\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', '\x3', 
		'\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC6', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\xC7', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\x44', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'\xCD', '\t', '\x4', '\x2', '\x2', '\xCA', '\xCC', '\t', '\x5', '\x2', 
		'\x2', '\xCB', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCF', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCD', 
		'\xCE', '\x3', '\x2', '\x2', '\x2', '\xCE', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xCD', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', '|', '\x86', 
		'\x91', '\xBA', '\xBF', '\xC5', '\xC7', '\xCD', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
