//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Exemplo.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class ExemploLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		ASSIGNMENT=1, PLUS_ASSIGNMENT=2, MINUS_ASSIGNMENT=3, DIV_ASSIGNMENT=4, 
		TIMES_ASSIGNMENT=5, GT=6, GE=7, LT=8, LE=9, EQ=10, NEQ=11, PLUS=12, MINUS=13, 
		DIV=14, TIMES=15, POW=16, LBRACE=17, RBRACE=18, LPAREN=19, RPAREN=20, 
		SEMI=21, COMMA=22, WHITESPACE=23, SINGLE_LINE_COMMENT=24, DELIMITED_COMMENT=25, 
		AND=26, OR=27, IF=28, ELSE=29, WHILE=30, COALESCE_OPERATOR=31, NULL=32, 
		VAR=33, NUMBER=34, VARIABLE=35;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"ASSIGNMENT", "PLUS_ASSIGNMENT", "MINUS_ASSIGNMENT", "DIV_ASSIGNMENT", 
		"TIMES_ASSIGNMENT", "GT", "GE", "LT", "LE", "EQ", "NEQ", "PLUS", "MINUS", 
		"DIV", "TIMES", "POW", "LBRACE", "RBRACE", "LPAREN", "RPAREN", "SEMI", 
		"COMMA", "WHITESPACE", "SINGLE_LINE_COMMENT", "DELIMITED_COMMENT", "AND", 
		"OR", "IF", "ELSE", "WHILE", "COALESCE_OPERATOR", "NULL", "VAR", "NUMBER", 
		"VARIABLE"
	};


	public ExemploLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ExemploLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "'+='", "'-='", "'/='", "'*='", "'>'", "'>='", "'<'", "'<='", 
		"'=='", "'!='", "'+'", "'-'", "'/'", "'*'", "'^'", "'{'", "'}'", "'('", 
		"')'", "';'", "','", null, null, null, "'&&'", "'||'", "'if'", "'else'", 
		"'while'", "'??'", "'null'", "'var'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "ASSIGNMENT", "PLUS_ASSIGNMENT", "MINUS_ASSIGNMENT", "DIV_ASSIGNMENT", 
		"TIMES_ASSIGNMENT", "GT", "GE", "LT", "LE", "EQ", "NEQ", "PLUS", "MINUS", 
		"DIV", "TIMES", "POW", "LBRACE", "RBRACE", "LPAREN", "RPAREN", "SEMI", 
		"COMMA", "WHITESPACE", "SINGLE_LINE_COMMENT", "DELIMITED_COMMENT", "AND", 
		"OR", "IF", "ELSE", "WHILE", "COALESCE_OPERATOR", "NULL", "VAR", "NUMBER", 
		"VARIABLE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Exemplo.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ExemploLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '%', '\xD4', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x6', '\x18', '\x7F', 
		'\n', '\x18', '\r', '\x18', '\xE', '\x18', '\x80', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\a', 
		'\x19', '\x89', '\n', '\x19', '\f', '\x19', '\xE', '\x19', '\x8C', '\v', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\a', '\x1A', '\x94', '\n', '\x1A', '\f', '\x1A', 
		'\xE', '\x1A', '\x97', '\v', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', ' ', 
		'\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '\"', 
		'\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x5', '#', '\xBF', 
		'\n', '#', '\x3', '#', '\x6', '#', '\xC2', '\n', '#', '\r', '#', '\xE', 
		'#', '\xC3', '\x3', '#', '\x3', '#', '\x6', '#', '\xC8', '\n', '#', '\r', 
		'#', '\xE', '#', '\xC9', '\x5', '#', '\xCC', '\n', '#', '\x3', '$', '\x3', 
		'$', '\a', '$', '\xD0', '\n', '$', '\f', '$', '\xE', '$', '\xD3', '\v', 
		'$', '\x4', '\x8A', '\x95', '\x2', '%', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', 
		'\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', 
		'\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', 
		';', '\x1F', '=', ' ', '?', '!', '\x41', '\"', '\x43', '#', '\x45', '$', 
		'G', '%', '\x3', '\x2', '\x6', '\x5', '\x2', '\v', '\f', '\xE', '\xF', 
		'\"', '\"', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x43', '\\', '\x61', 
		'\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', 
		'\x61', '\x63', '|', '\x2', '\xDB', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'G', '\x3', '\x2', '\x2', '\x2', '\x3', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\x5', 'K', '\x3', '\x2', '\x2', '\x2', '\a', 'N', '\x3', '\x2', '\x2', 
		'\x2', '\t', 'Q', '\x3', '\x2', '\x2', '\x2', '\v', 'T', '\x3', '\x2', 
		'\x2', '\x2', '\r', 'W', '\x3', '\x2', '\x2', '\x2', '\xF', 'Y', '\x3', 
		'\x2', '\x2', '\x2', '\x11', '\\', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'^', '\x3', '\x2', '\x2', '\x2', '\x15', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '\x64', '\x3', '\x2', '\x2', '\x2', '\x19', 'g', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', 'i', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'k', '\x3', '\x2', '\x2', '\x2', '\x1F', 'm', '\x3', '\x2', '\x2', '\x2', 
		'!', 'o', '\x3', '\x2', '\x2', '\x2', '#', 'q', '\x3', '\x2', '\x2', '\x2', 
		'%', 's', '\x3', '\x2', '\x2', '\x2', '\'', 'u', '\x3', '\x2', '\x2', 
		'\x2', ')', 'w', '\x3', '\x2', '\x2', '\x2', '+', 'y', '\x3', '\x2', '\x2', 
		'\x2', '-', '{', '\x3', '\x2', '\x2', '\x2', '/', '~', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x84', '\x3', '\x2', '\x2', '\x2', '\x33', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\x39', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', ';', '\xA6', '\x3', '\x2', '\x2', '\x2', '=', '\xAB', '\x3', '\x2', 
		'\x2', '\x2', '?', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x41', '\xB4', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\xB9', '\x3', '\x2', '\x2', '\x2', 
		'\x45', '\xBE', '\x3', '\x2', '\x2', '\x2', 'G', '\xCD', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'J', '\a', '?', '\x2', '\x2', 'J', '\x4', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'L', '\a', '-', '\x2', '\x2', 'L', 'M', '\a', '?', 
		'\x2', '\x2', 'M', '\x6', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\a', 
		'/', '\x2', '\x2', 'O', 'P', '\a', '?', '\x2', '\x2', 'P', '\b', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'R', '\a', '\x31', '\x2', '\x2', 'R', 'S', '\a', 
		'?', '\x2', '\x2', 'S', '\n', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', 
		',', '\x2', '\x2', 'U', 'V', '\a', '?', '\x2', '\x2', 'V', '\f', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'X', '\a', '@', '\x2', '\x2', 'X', '\xE', '\x3', 
		'\x2', '\x2', '\x2', 'Y', 'Z', '\a', '@', '\x2', '\x2', 'Z', '[', '\a', 
		'?', '\x2', '\x2', '[', '\x10', '\x3', '\x2', '\x2', '\x2', '\\', ']', 
		'\a', '>', '\x2', '\x2', ']', '\x12', '\x3', '\x2', '\x2', '\x2', '^', 
		'_', '\a', '>', '\x2', '\x2', '_', '`', '\a', '?', '\x2', '\x2', '`', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\a', '?', '\x2', 
		'\x2', '\x62', '\x63', '\a', '?', '\x2', '\x2', '\x63', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x64', '\x65', '\a', '#', '\x2', '\x2', '\x65', 
		'\x66', '\a', '?', '\x2', '\x2', '\x66', '\x18', '\x3', '\x2', '\x2', 
		'\x2', 'g', 'h', '\a', '-', '\x2', '\x2', 'h', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'j', '\a', '/', '\x2', '\x2', 'j', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'k', 'l', '\a', '\x31', '\x2', '\x2', 'l', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', 'm', 'n', '\a', ',', '\x2', '\x2', 'n', ' ', '\x3', '\x2', 
		'\x2', '\x2', 'o', 'p', '\a', '`', '\x2', '\x2', 'p', '\"', '\x3', '\x2', 
		'\x2', '\x2', 'q', 'r', '\a', '}', '\x2', '\x2', 'r', '$', '\x3', '\x2', 
		'\x2', '\x2', 's', 't', '\a', '\x7F', '\x2', '\x2', 't', '&', '\x3', '\x2', 
		'\x2', '\x2', 'u', 'v', '\a', '*', '\x2', '\x2', 'v', '(', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'x', '\a', '+', '\x2', '\x2', 'x', '*', '\x3', '\x2', 
		'\x2', '\x2', 'y', 'z', '\a', '=', '\x2', '\x2', 'z', ',', '\x3', '\x2', 
		'\x2', '\x2', '{', '|', '\a', '.', '\x2', '\x2', '|', '.', '\x3', '\x2', 
		'\x2', '\x2', '}', '\x7F', '\t', '\x2', '\x2', '\x2', '~', '}', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\b', 
		'\x18', '\x2', '\x2', '\x83', '\x30', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x85', '\a', '\x31', '\x2', '\x2', '\x85', '\x86', '\a', '\x31', '\x2', 
		'\x2', '\x86', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x87', '\x89', '\v', 
		'\x2', '\x2', '\x2', '\x88', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x8C', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\b', '\x19', '\x2', '\x2', '\x8E', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\a', '\x31', '\x2', '\x2', '\x90', '\x91', '\a', 
		',', '\x2', '\x2', '\x91', '\x95', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x94', '\v', '\x2', '\x2', '\x2', '\x93', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x97', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\x3', 
		'\x2', '\x2', '\x2', '\x95', '\x93', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x99', '\a', ',', '\x2', '\x2', '\x99', '\x9A', '\a', 
		'\x31', '\x2', '\x2', '\x9A', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9B', 
		'\x9C', '\b', '\x1A', '\x2', '\x2', '\x9C', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\x9D', '\x9E', '\a', '(', '\x2', '\x2', '\x9E', '\x9F', '\a', 
		'(', '\x2', '\x2', '\x9F', '\x36', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\xA1', '\a', '~', '\x2', '\x2', '\xA1', '\xA2', '\a', '~', '\x2', '\x2', 
		'\xA2', '\x38', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\a', 'k', 
		'\x2', '\x2', '\xA4', '\xA5', '\a', 'h', '\x2', '\x2', '\xA5', ':', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA7', '\a', 'g', '\x2', '\x2', '\xA7', 
		'\xA8', '\a', 'n', '\x2', '\x2', '\xA8', '\xA9', '\a', 'u', '\x2', '\x2', 
		'\xA9', '\xAA', '\a', 'g', '\x2', '\x2', '\xAA', '<', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xAC', '\a', 'y', '\x2', '\x2', '\xAC', '\xAD', '\a', 
		'j', '\x2', '\x2', '\xAD', '\xAE', '\a', 'k', '\x2', '\x2', '\xAE', '\xAF', 
		'\a', 'n', '\x2', '\x2', '\xAF', '\xB0', '\a', 'g', '\x2', '\x2', '\xB0', 
		'>', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\a', '\x41', '\x2', 
		'\x2', '\xB2', '\xB3', '\a', '\x41', '\x2', '\x2', '\xB3', '@', '\x3', 
		'\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', 'p', '\x2', '\x2', '\xB5', 
		'\xB6', '\a', 'w', '\x2', '\x2', '\xB6', '\xB7', '\a', 'n', '\x2', '\x2', 
		'\xB7', '\xB8', '\a', 'n', '\x2', '\x2', '\xB8', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\xB9', '\xBA', '\a', 'x', '\x2', '\x2', '\xBA', '\xBB', 
		'\a', '\x63', '\x2', '\x2', '\xBB', '\xBC', '\a', 't', '\x2', '\x2', '\xBC', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBF', '\a', '/', '\x2', 
		'\x2', '\xBE', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xC2', '\t', '\x3', '\x2', '\x2', '\xC1', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\xC2', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xCB', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC7', '\a', '\x30', '\x2', 
		'\x2', '\xC6', '\xC8', '\t', '\x3', '\x2', '\x2', '\xC7', '\xC6', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCA', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xC5', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCC', 
		'\x46', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xD1', '\t', '\x4', '\x2', 
		'\x2', '\xCE', '\xD0', '\t', '\x5', '\x2', '\x2', '\xCF', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD2', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', 'H', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD1', '\x3', 
		'\x2', '\x2', '\x2', '\v', '\x2', '\x80', '\x8A', '\x95', '\xBE', '\xC3', 
		'\xC9', '\xCB', '\xD1', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
